// <auto-generated />
using System;
using ES.BS.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ES.BS.DataAccessLayer.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ES.BS.Model.BuildingSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Generator_Staus")
                        .HasColumnType("bit");

                    b.Property<int?>("NoOfFloors")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BuildingSystemss");
                });

            modelBuilder.Entity("ES.BS.Model.PersonDatabase", b =>
                {
                    b.Property<Guid>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("fromFloor")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("toFloor")
                        .HasColumnType("tinyint");

                    b.Property<int?>("weight")
                        .HasColumnType("int");

                    b.HasKey("personId");

                    b.ToTable("PersonDet");
                });

            modelBuilder.Entity("ES.BS.Model.WorkerDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("workerDetailss");
                });
#pragma warning restore 612, 618
        }
    }
}
