// <auto-generated />
using System;
using ES.ElevatorDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ES.ElevatorDataAccess.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20230705044754_Firstmig")]
    partial class Firstmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ES.ElevatorModel.PersonDatabase", b =>
                {
                    b.Property<Guid>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("fromFloor")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("toFloor")
                        .HasColumnType("tinyint");

                    b.Property<int?>("weight")
                        .HasColumnType("int");

                    b.HasKey("personId");

                    b.ToTable("PersonDet");
                });
#pragma warning restore 612, 618
        }
    }
}
